version: "3.8"

services:
#  app:
#    build: .
#    restart: always
#    volumes:
#      - .:/code
#    environment:
#      - CURRENT_ENV=prod
#    ports:
#    - "8000:8000"
#    env_file:
#      - .env

  app:
    build: .
#      args:
#        CURRENT_ENV: dev
    restart: always
    volumes:
    - .:/code
    environment:
      - CURRENT_ENV=prod
    ports:
    - "8000:8000"
    command: uvicorn src.life.app:app --host $server_host --port $server_port --reload
    env_file:
      - .env
